version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: "postgres"
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - twix-volume:/var/lib/postgresql/data

volumes:
  twix-volume:

networks:
  default:
    name: twix
